apiVersion: v1        ##版本号
kind: Service        ##服务类型
metadata:
  name: mysql
  namespace: publish-service
  labels:
    app: mysql
spec:
  type: NodePort     ##端口映射
  ports:
    - port: 3306 		##内部端口
      targetPort: 3306   ##映射端口
      nodePort: 30306   ## 对外暴露的端口
  selector:       ##选择器/
    app: mysql		##选择业务进行发布