apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  namespace: publish-service
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: root@k8s_master:/home/lzy/dockerTest/mysql_build# cat ~/.docker/config.json | base64
    ewoJImF1dGhzIjogewoJCSIxOTIuMTY4LjE5NS4xMzE6NTAwMCI6IHsKCQkJImF1dGgiOiAiYkhw
    NU9teDZlVEV5TXc9PSIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50Ijog
    IkRvY2tlci1DbGllbnQvMTkuMDMuMTQgKGxpbnV4KSIKCX0KfQ==